### ISSUE TITLE
Change Normal{P,X} to Normal{X,P}

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureTheory.jl#13]
@phipsgabler suggested this, so users can write, e.g., 
```julia
Normal{Float64}
```

instead of

```julia
Normal{P,Float64} where {P}
```

Any objections @mschauer @simeonschaub @femtomc ?

**Comment by cscherrer** [comment]
To be clear, this is just an example - we need a general pattern for measures that can follow different parameterizations.

One possible counterargument: The current setup makes it a bit easier to talk about generic measure types on X, since we can have e.g.
```julia
M{Float64}
```

and `M` might be `Lebesgue` or `Normal{P}` for some `P`

**Comment by mschauer** [comment]
in favor, there might be no P at all.

**Comment by cscherrer** [comment]
> in favor, there might be no P at all.

Good point. And e.g. `Array{T,N}` is a a generalization of `Vector{T}`, also an argument toward "put `X` first". Are there standard Julia examples that go the other way? If not I'd say the change is the way to go.

**Comment by cscherrer** [comment]
Since `X` can be determined statically from `P`, we might not need `X` to be in the type anyway. Let's try it out this way and see how it goes - we can come back to this if we need to. I'll close this now.
