### ISSUE TITLE
Statement of Need

### ISSUE THREAD

**Issue by ludgerpaehler** [cscherrer/MeasureTheory.jl#179]
Per Review Criteria

> Do the authors clearly state what problems the software is designed to solve and who the target audience is?

I believe what would really help here is to more clearly establish the rules underlying the definition of a measure in the "Why", hence leading into the definition of a probability measure essentially adding the probability constraint. As is, the "Why" is a little hard to read for someone who does not already know measure theory.

**Comment by cscherrer** [comment]
Hi @ludgerpaehler , @mschauer and I were just discussing this. Most things under "Documentation" in the criteria seem to be about the repository, not the paper. Just to be sure we understand right, would adding this information in the documentation address your concern?

**Comment by ludgerpaehler** [comment]
@cscherrer sorry for the belated reply, yes, absolutely! My concerns were mostly about the docs :)

**Comment by mschauer** [comment]
#199 now gives context and states the core audience (powering PPL work in Julia behind the scenes)

**Comment by cscherrer** [comment]
Ok to close @ludgerpaehler ?

**Comment by ludgerpaehler** [comment]
Sounds good to me!
