### ISSUE TITLE
Zenodo integration and DOI'd version for paper

### ISSUE THREAD

**Issue by mschauer** [cscherrer/MeasureTheory.jl#214]
Zenodo has Github integration.

Step 1: @cscherrer make an account and link it to your Github account. Flipping the switch for this repo.
Step 2: Tag a release.

<img width="870" alt="Screen Shot 2022-07-01 at 10 58 22" src="https://user-images.githubusercontent.com/1923437/176862022-e526388d-0d64-45a3-b71b-e28d29e21b96.png">

**Comment by cscherrer** [comment]
Looks like it's already done:
[![DOI](https://zenodo.org/badge/233287642.svg)](https://zenodo.org/badge/latestdoi/233287642)

**Comment by cscherrer** [comment]
Posted this in the review thread, closing now. Thanks @mschauer
