### ISSUE TITLE
WARNING: both MeasureTheory and TransformVariables export "as"; uses of it in module Main must be qualified

### ISSUE THREAD

**Issue by jfb-h** [cscherrer/MeasureTheory.jl#225]
Right now, MeasureTheory and TransformVariables both export `as`. Is that on purpose or should MeasureTheory extend `TransformVariables.as`?

**Comment by cscherrer** [comment]
It's currently kind of a hack, meant to be temporary. 

The `as` interface is pretty great, and I wanted to be able to extend it easily without type piracy. So MeasureTheory currently has
```julia
import TransformVariables
const TV = TransformVariables

as(args...; kwargs...) = TV.as(args...; kwargs...)
```

I think the current would-be piracy is all for `as(::Distribution)` methods. Now that we have DistributionMeasures.jl, we could probably get rid of this. But before long, I think we may move away from TransformVariables anyway, for a few reasons:

1. A value drawn from one measure may sometimes affect the support of another. I don't think TV has a way to address this
2. TV uses `Int` type parameters, but I think we'll want to allow for statically-sized arrays, which can be much more efficient
3. As a personal preference, I'd like transforms to be callable. TV used to have this, but now disallows `my_transform(x)`, instead requiring `transform(my_transform, x)`

**Comment by jfb-h** [comment]
> I wanted to be able to extend it easily without type piracy

I see, that makes sense. I was trying out MeasureTheory with the LogDensityProblems stack, which was very nice but having to put `TV.as` everywhere was a bit strange.

Thanks for the heads up!
