### ISSUE TITLE
name clash with https://github.com/JuliaGraphics/Measures.jl

### ISSUE THREAD

**Issue by bjarthur** [cscherrer/MeasureTheory.jl#3]
might consider calling this package something else

**Comment by cscherrer** [comment]
Thanks, it's really unfortunate the the namespace is getting more crowded, and for now there's not really a better name than "Measures.jl" for a package that's all about measures in the classical sense. After some discussion about this on the Julia Slack, it seems there's development in the works to allow specification as `]add cscherrer/Measures`.

 I'll be more concerned about this as we get close to registering the package.

**Comment by DilumAluthge** [comment]
ProbabilityMeasures.jl? Since that seems to be the main motivating use case.

MeasureTheory.jl? A little more general.

**Comment by DilumAluthge** [comment]
> After some discussion about this on the Julia Slack, it seems there's development in the works to allow specification as `]add cscherrer/Measures`.

Unlikely that this will be finalized anytime soon.

**Comment by mschauer** [comment]
`RandomVariables.jl`?

**Comment by cscherrer** [comment]
`ProbabilityMeasures` and `RandomVariables` both imply this is limited to probability, which it's not. `MeasureTheory` is pretty good, only concern is that people might incorrectly assume it's not applied.

Right now I'm thinking either `MeasureTheory` or `PositiveMeasures`. The latter leaves an obvious opening for `SignedMeasures`, which are important for some applications.

**Comment by mschauer** [comment]
I was thinking: At least some people know what random variables and probability distributions are, fewer know what positive measures are.

**Comment by DilumAluthge** [comment]
> `MeasureTheory` is pretty good, only concern is that people might incorrectly assume it's not applied.

AppliedMeasureTheory.jl?

Or maybe MeasureTheoryApplications.jl?

**Comment by DilumAluthge** [comment]
I would go with MeasureTheory.jl over PositiveMeasures.jl.

**Comment by cscherrer** [comment]
Reluctantly renamed to MeasureTheory.jl. So much for symmetry :(
