### ISSUE TITLE
Absolute continuity

### ISSUE THREAD

**Issue by mschauer** [cscherrer/MeasureTheory.jl#6]
https://github.com/cscherrer/Measures.jl/blob/84a22ad584e29670b9685e38e3a7bf52b8cff691/src/basemeasures.jl#L22

If the density is zero somewhere, then even if the base measures are the same, the measures are not equivalent.

**Comment by cscherrer** [comment]
Hi @mschauer , I'm just getting back to working on this, and didn't see the notofication - sorry for the long wait :) 

This is a great point! I'm really still thinking through the right to set all of this up. I haven't been very clear yet about goals for this package, I think I'll spend some time on this today and hopefully get into a better place to move things forward efficiently.

**Comment by mschauer** [comment]
Something reasonable would be a trait Which guarantees positivity of the density

**Comment by cscherrer** [comment]
We need a way to represent the support of a measure. I've looked a bit at [DomainSets](https://github.com/JuliaApproximation/DomainSets.jl) for this, but I don't have a deep understanding of it. Any other ideas?

**Comment by cscherrer** [comment]
I've taken out the offending methods, and added simplified ones in https://github.com/cscherrer/MeasureTheory.jl/commit/600060ed464224ff5a6f77a57e6c0e3b45681c89. Closing this now

**Comment by mschauer** [comment]
I approve 😄

**Comment by cscherrer** [comment]
Was this rude of me? I often see code "owners" close issues based on their judgement. But maybe not for collaborators? I hope I didn't overstep here. Maybe there's a standard I don't know about, or maybe we should make one?

**Comment by mschauer** [comment]
I was just happy with the general direction this took, no subtext or concealed criticism
