### ISSUE TITLE
`logdensity`: Should new measures use 2-arg or 3-arg method?

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureTheory.jl#99]
In the current definition of a standard normal (let's use this as a running example) we have
```julia
logdensity(d::Normal{()} , x) = - x^2 / 2 
```

Implicit in this is that this log-density is with respect to the base measure
```julia
basemeasure(::Normal{()}) = (1/sqrt2π) * Lebesgue(ℝ)
```

If we want to compute the log-density wrt a _different_ base measure, we can use the three-argument form, 
```julia
logdensity(μ::AbstractMeasure, ν::AbstractMeasure, x)
```

I think the implementation of this will change, for example to something like
```julia
function logdensity(μ::AbstractMeasure, ν::AbstractMeasure, x)
    a = basemeasure(μ)
    b = basemeasure(ν)

    ℓ = logdensity(μ, x)        # implicitly wrt a
    ℓ += logdensity(a, b, x)    # total is now logdensity(μ, b, x)
    ℓ -= logdensity(ν, x)       # impicitly wrt b, yielding final total
    return ℓ
end
```

In general this might be recursive, because of `logdensity(a, b, x)`. Of course we can rework this to avoid the recursion, this is more to define the behavior than anything.

Alternatively, we could start by defining the three-argument form (suggested by @mschauer in https://github.com/cscherrer/MeasureTheory.jl/pull/93#discussion_r642050446), and have the two-argument form as an extra convenience.

There are a few things I like about the current approach:
- It simplifies defining a `logdensity`, and reduces the chance of ending up with lots of different methods that may be inconsistent
- It optimizes for the most common use case, where users can work with a measure similarly to a distribution

Moritz, what do advantages do you see of building things on the three-argument form? Anyone else have thought on this?

**Comment by cscherrer** [comment]
I just realized there's another big advantage - whatever we do here, we'll need to do in Soss as well. Soss is usable an unspecified base measure (and we can always find it when we need it). Requiring three arguments in this case would add overhead to the codegen. I think this might make it a no-go.

I have a branch here with the two-argument approach fleshed out a little more:
https://github.com/cscherrer/MeasureTheory.jl/tree/cs-densities

For example,
```julia
julia> logdensity(Lebesgue(ℝ), Lebesgue(ℝ), 0.2)
0.0

julia> logdensity(Dirac(2),Dirac(2), 2)
0.0

julia> logdensity(Dirac(2),Dirac(2), 3)
-Inf

julia> logdensity(Dirac(3),Dirac(2), 3)
Inf

julia> logdensity(Dirac(3),Dirac(2), 2)
-Inf

julia> logdensity(Normal(), Cauchy(), 0.2)
0.24501206579800872

julia> logdensity(Normal(), Cauchy(), 100)
-4990.563768280379
```

**Comment by cscherrer** [comment]
Another example:
```julia
julia> using Symbolics

julia> @variables x μ σ
3-element Vector{Num}:
 x
 μ
 σ

julia> logdensity(Normal(μ,σ), x)
-log(σ) - (0.5(σ^-2)*((x - μ)^2))

julia> logdensity(Normal(μ,σ), basemeasure(Normal(μ,σ)), x)
-log(σ) - (0.5(σ^-2)*((x - μ)^2))

julia> logdensity(Normal(μ,σ), Lebesgue(ℝ), x)
-0.9189385332046728 - log(σ) - (0.5(σ^-2)*((x - μ)^2))
```

**Comment by mschauer** [comment]
I convinced myself that everything is fine as by construction 2-arg `basemeasure` and `logpdf` do not duplicate information, so they are always mutually consistent.
